apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cronjob-rolebinding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd2  # Ensure this matches your Argocd namespace
roleRef:
  kind: ClusterRole
  name: argocd-cronjob-role
  apiGroup: rbac.authorization.k8s.io
