apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: nishit7908/myapp:b983d4e159aebe1078081bea5d2d36e1a1408508
        ports:
        - containerPort: 5001
