apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: nishit7908/myapp:ceb55e4b4ca14e1ce1c7bdb66aa87033adbc1b2f
        ports:
        - containerPort: 5001
