name: testing our application
on:
  push:
    branches:
      - main
    paths:
      - "**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Docker Setup
        uses: docker/setup-buildx-action@v1
        with:
          login-server: "docker.io"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest
      - name: Build Docker Image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest
      - name: Push DOcker Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}